use std::io::{self, Read as IoRead, Write as IoWrite};
use std::net::SocketAddr;
use std::sync::Arc;
use std::task::{Context, Poll};

use hyper::rt::{Read, ReadBufCursor, Write};
use mio::net::TcpStream;
use rustls::client::danger::{HandshakeSignatureValid, ServerCertVerified, ServerCertVerifier};
use rustls::crypto::aws_lc_rs::default_provider;
use rustls::pki_types::{CertificateDer, UnixTime};
use rustls::{ClientConfig, ClientConnection, RootCertStore, pki_types::ServerName};
use rustls::{DigitallySignedStruct, SignatureScheme};

pub struct AsyncTlsStream {
    socket: TcpStream,
    tls_conn: ClientConnection,
}

pub struct AsyncTcpStream(TcpStream);

impl AsyncTlsStream {
    pub fn connect(addr: SocketAddr, server_name: &str) -> std::io::Result<Self> {
        let socket = TcpStream::connect(addr)?;
        let server_name = ServerName::try_from(server_name)
            .map_err(|e| io::Error::new(io::ErrorKind::InvalidInput, e.to_string()))?
            .to_owned();
        let config = make_config();
        let tls_conn = ClientConnection::new(config.clone(), server_name)
            .map_err(|e| io::Error::other(e.to_string()))?;

        // FIXME: mio docs say I need to wait for a (writable) event and check TcpStream::take_err?

        Ok(Self { socket, tls_conn })
    }
}

impl Read for AsyncTlsStream {
    fn poll_read(
        self: std::pin::Pin<&mut Self>,
        cx: &mut Context<'_>,
        mut buf: ReadBufCursor<'_>,
    ) -> Poll<Result<(), io::Error>> {
        let this = self.get_mut();

        // Flush pending TLS data first (e.g. handshake messages from a prior
        // process_new_packets call).  If we only flush *after* read_tls, we miss
        // the case where the socket has nothing to read yet but the server is
        // waiting for our Finished — the handshake deadlocks and the server
        // eventually closes the connection.
        if this.tls_conn.wants_write() {
            match this.tls_conn.write_tls(&mut this.socket) {
                Ok(_) => {}
                Err(e) if is_pending_socket_error(&e) => {}
                Err(e) => return Poll::Ready(Err(e)),
            }
        }

        // `read_tls` returning `Ok(0)` is a TCP-level EOF (the peer closed the
        // socket); `WouldBlock` just means no new bytes are available yet. In both
        // cases we still fall through to drain any plaintext rustls has already
        // decrypted — returning early on `WouldBlock` would strand buffered bytes.
        let socket_eof = match this.tls_conn.read_tls(&mut this.socket) {
            Err(e) if !is_pending_socket_error(&e) => return Poll::Ready(Err(e)),
            Err(_) => false,
            Ok(0) => true,
            Ok(_) => false,
        };

        let io_state = match this.tls_conn.process_new_packets() {
            Ok(state) => state,
            Err(e) => {
                return Poll::Ready(Err(io::Error::new(
                    io::ErrorKind::InvalidData,
                    e.to_string(),
                )));
            }
        };

        // Flush any new TLS data generated by process_new_packets.
        if this.tls_conn.wants_write() {
            let _ = this.tls_conn.write_tls(&mut this.socket);
        }

        let plaintext_len = io_state.plaintext_bytes_to_read();
        if plaintext_len > 0 {
            // Safety: we write exactly `to_read` bytes before advancing the cursor
            let dst = unsafe { buf.as_mut() };
            let to_read = plaintext_len.min(dst.len());
            let dst_slice =
                unsafe { std::slice::from_raw_parts_mut(dst.as_mut_ptr() as *mut u8, to_read) };
            let n = this.tls_conn.reader().read(dst_slice)?;
            unsafe { buf.advance(n) };
            return Poll::Ready(Ok(()));
        }

        // A zero-length read tells hyper the body is complete. Without surfacing
        // EOF here, a response delimited by connection close (no Content-Length,
        // or a close without a TLS close_notify) spins forever — which is what
        // hung Telegram file downloads after the bytes had already arrived.
        if io_state.peer_has_closed() || socket_eof {
            return Poll::Ready(Ok(()));
        }

        cx.waker().wake_by_ref();
        Poll::Pending
    }
}

impl Write for AsyncTlsStream {
    fn poll_write(
        self: std::pin::Pin<&mut Self>,
        cx: &mut Context<'_>,
        buf: &[u8],
    ) -> Poll<Result<usize, io::Error>> {
        let this = self.get_mut();

        // Drain the TLS write buffer first so rustls's plaintext buffer has room.
        // rustls caps sendable_plaintext at 64 KB; if it's full, writer().write()
        // returns Ok(0), which hyper treats as a terminal write error.
        if this.tls_conn.wants_write() {
            match this.tls_conn.write_tls(&mut this.socket) {
                Ok(_) => {}
                Err(e) if is_pending_socket_error(&e) => {}
                Err(e) => return Poll::Ready(Err(e)),
            }
        }

        let n = this.tls_conn.writer().write(buf)?;
        let _ = this.tls_conn.write_tls(&mut this.socket);

        if n == 0 && !buf.is_empty() {
            // Buffer still full after draining; yield and retry.
            cx.waker().wake_by_ref();
            return Poll::Pending;
        }

        Poll::Ready(Ok(n))
    }

    fn poll_flush(
        self: std::pin::Pin<&mut Self>,
        cx: &mut Context<'_>,
    ) -> Poll<Result<(), io::Error>> {
        let this = self.get_mut();
        while this.tls_conn.wants_write() {
            match this.tls_conn.write_tls(&mut this.socket) {
                Ok(_) => {}
                Err(e) if is_pending_socket_error(&e) => {
                    cx.waker().wake_by_ref();
                    return Poll::Pending;
                }
                Err(e) => return Poll::Ready(Err(e)),
            }
        }
        Poll::Ready(Ok(()))
    }

    fn poll_shutdown(
        self: std::pin::Pin<&mut Self>,
        cx: &mut Context<'_>,
    ) -> Poll<Result<(), io::Error>> {
        let this = self.get_mut();
        this.tls_conn.send_close_notify();
        while this.tls_conn.wants_write() {
            match this.tls_conn.write_tls(&mut this.socket) {
                Ok(_) => {}
                Err(e) if is_pending_socket_error(&e) => {
                    cx.waker().wake_by_ref();
                    return Poll::Pending;
                }
                Err(e) => return Poll::Ready(Err(e)),
            }
        }
        Poll::Ready(Ok(()))
    }
}

impl AsyncTcpStream {
    pub fn new(addr: SocketAddr) -> std::io::Result<Self> {
        let conn = TcpStream::connect(addr)?;

        // FIXME: mio docs say I need to wait for a (writable) event and check TcpStream::take_err?

        Ok(Self(conn))
    }
}

impl Read for AsyncTcpStream {
    fn poll_read(
        self: std::pin::Pin<&mut Self>,
        cx: &mut Context<'_>,
        mut buf: ReadBufCursor<'_>,
    ) -> Poll<Result<(), io::Error>> {
        // Safety: we write exactly `n` bytes before advancing the cursor
        let dst = unsafe { buf.as_mut() };
        let dst_slice =
            unsafe { std::slice::from_raw_parts_mut(dst.as_mut_ptr() as *mut u8, dst.len()) };
        match self.get_mut().0.read(dst_slice) {
            Ok(n) => {
                unsafe { buf.advance(n) };
                Poll::Ready(Ok(()))
            }
            Err(e) if is_pending_socket_error(&e) => {
                cx.waker().wake_by_ref();
                Poll::Pending
            }
            Err(e) => Poll::Ready(Err(e)),
        }
    }
}

impl Write for AsyncTcpStream {
    fn poll_write(
        self: std::pin::Pin<&mut Self>,
        cx: &mut Context<'_>,
        buf: &[u8],
    ) -> Poll<Result<usize, io::Error>> {
        match self.get_mut().0.write(buf) {
            Ok(n) => Poll::Ready(Ok(n)),
            Err(e) if is_pending_socket_error(&e) => {
                cx.waker().wake_by_ref();
                Poll::Pending
            }
            Err(e) => Poll::Ready(Err(e)),
        }
    }

    fn poll_flush(
        self: std::pin::Pin<&mut Self>,
        _cx: &mut Context<'_>,
    ) -> Poll<Result<(), io::Error>> {
        Poll::Ready(self.get_mut().0.flush())
    }

    fn poll_shutdown(
        self: std::pin::Pin<&mut Self>,
        _cx: &mut Context<'_>,
    ) -> Poll<Result<(), io::Error>> {
        Poll::Ready(self.get_mut().0.shutdown(std::net::Shutdown::Write))
    }
}

fn make_config() -> Arc<ClientConfig> {
    let mut root_store = RootCertStore::empty();
    root_store.extend(webpki_roots::TLS_SERVER_ROOTS.iter().cloned());
    let mut config = ClientConfig::builder_with_provider(Arc::new(default_provider()))
        .with_safe_default_protocol_versions()
        .expect("default TLS versions are valid")
        .with_root_certificates(root_store)
        .with_no_client_auth();
    if std::env::var_os("TINYNET_INSECURE_TLS").is_some() {
        config
            .dangerous()
            .set_certificate_verifier(Arc::new(NoCertificateVerification));
    }
    Arc::new(config)
}

#[derive(Debug)]
struct NoCertificateVerification;

impl ServerCertVerifier for NoCertificateVerification {
    fn verify_server_cert(
        &self,
        _end_entity: &CertificateDer<'_>,
        _intermediates: &[CertificateDer<'_>],
        _server_name: &ServerName<'_>,
        _ocsp_response: &[u8],
        _now: UnixTime,
    ) -> Result<ServerCertVerified, rustls::Error> {
        Ok(ServerCertVerified::assertion())
    }

    fn verify_tls12_signature(
        &self,
        _message: &[u8],
        _cert: &CertificateDer<'_>,
        _dss: &DigitallySignedStruct,
    ) -> Result<HandshakeSignatureValid, rustls::Error> {
        Ok(HandshakeSignatureValid::assertion())
    }

    fn verify_tls13_signature(
        &self,
        _message: &[u8],
        _cert: &CertificateDer<'_>,
        _dss: &DigitallySignedStruct,
    ) -> Result<HandshakeSignatureValid, rustls::Error> {
        Ok(HandshakeSignatureValid::assertion())
    }

    fn supported_verify_schemes(&self) -> Vec<SignatureScheme> {
        vec![
            SignatureScheme::RSA_PKCS1_SHA256,
            SignatureScheme::RSA_PKCS1_SHA384,
            SignatureScheme::RSA_PKCS1_SHA512,
            SignatureScheme::ECDSA_NISTP256_SHA256,
            SignatureScheme::ECDSA_NISTP384_SHA384,
            SignatureScheme::ED25519,
            SignatureScheme::RSA_PSS_SHA256,
            SignatureScheme::RSA_PSS_SHA384,
            SignatureScheme::RSA_PSS_SHA512,
        ]
    }
}

fn is_pending_socket_error(err: &io::Error) -> bool {
    matches!(
        err.kind(),
        io::ErrorKind::WouldBlock | io::ErrorKind::NotConnected | io::ErrorKind::Interrupted
    )
}
