name: Build and Test

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always
  INSTA_UPDATE: no
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Test (${{ inputs.os }})
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install system deps (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install -y capnproto libssl-dev

      - name: Install system deps (macOS)
        if: runner.os == 'macOS'
        run: brew install capnp

      - name: Install system deps (Windows)
        if: runner.os == 'Windows'
        run: choco install capnproto

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: server/frontend/pnpm-lock.yaml

      - uses: dtolnay/rust-toolchain@stable

      - name: Disable rust-lld (Linux)
        if: runner.os == 'Linux'
        run: echo "RUSTFLAGS=-Clinker-features=-lld" >> "$GITHUB_ENV"

      - uses: Swatinem/rust-cache@v2

      - uses: taiki-e/install-action@v2
        with:
          tool: nextest

      - name: Build
        run: cargo build --release --workspace --all-targets

      - name: Test
        run: cargo nextest run --release --workspace --profile ci

      - name: Report test results
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Tests (${{ inputs.os }})
          path: target/nextest/ci/junit.xml
          reporter: java-junit
