name: Nightly

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  checks: write
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    uses: ./.github/workflows/_build-test.yml
    with:
      os: ${{ matrix.os }}
    permissions:
      checks: write
      contents: read
